#!/usr/bin/env bash

while read os arch; do
  identifier="spotcast-$1-$os"-"$arch"
  build_dir="pkg/$identifier"
  mkdir -p "$build_dir"
  echo "Compiling for $os/$arch"

  GOOS=$os GOARCH=$arch go build -o "$build_dir"/spotcast-$1 src/$1/*.go    &&
    cd pkg && tar -zcvf "$identifier".tar.gz "$identifier"     &&
    rm -rf "$identifier" && cd ..
done << EOF
darwin 386
darwin amd64
dragonfly amd64
freebsd 386
linux 386
linux amd64
netbsd  386
netbsd  amd64
openbsd 386
openbsd amd64
windows 386
windows amd64
EOF
wait

echo "All Done"
